/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/accounts/{accountId}:block": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bloqueia outra conta
         * @description Idempotente: bloquear quem já está bloqueado também responde 204 e mantém a data do primeiro bloqueio. A resposta é a mesma se a outra pessoa tiver bloqueado você.
         */
        post: operations["blockAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{accountId}:unblock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Desfaz o próprio bloqueio de outra conta
         * @description Idempotente: sem bloqueio, ou com id que não é de conta, também responde 204. Um bloqueio que a outra pessoa fez continua valendo.
         */
        post: operations["unblockAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cria um evento em rascunho
         * @description O rascunho só aparece para o ADMIN até ser publicado. Sem Idempotency-Key: repetir a criação gera outro rascunho, que o ADMIN cancela (docs/adr/0016).
         */
        post: operations["createEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/events/{eventId}/rounds/{number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lê uma rodada do evento
         * @description Quantos pares se formaram e quantas pessoas ficaram de fora, nunca quem.
         */
        get: operations["getRound"];
        /**
         * Inicia uma rodada de pareamento do evento
         * @description Sem corpo. Sorteia os pares entre os inscritos: o máximo de pares possível, sem par bloqueado nem par que já se formou no evento, com prioridade para quem ficou de fora mais vezes. Idempotente pela chave evento + número: repetir, inclusive ao mesmo tempo, devolve a mesma rodada, por isso dispensa If-Match e Idempotency-Key (docs/adr/0017). A rodada N exige a N-1, e o evento precisa estar publicado e em andamento.
         */
        put: operations["startRound"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lê um evento, inclusive rascunho
         * @description Traz o estado guardado e quantas pessoas se inscreveram, nunca quem.
         */
        get: operations["getAdminEvent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/events/{id}:cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancela um evento
         * @description Vale para rascunho ou publicado que ainda não acabou, inclusive em andamento. O evento continua visível, para quem se inscreveu saber, e não aceita inscrições. Repetir responde 409 sem mudar nada.
         */
        post: operations["cancelEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/events/{id}:publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publica um rascunho
         * @description O evento passa a aparecer para quem está logado e aceita inscrições. Só vale para rascunho que ainda não começou; repetir responde 409 sem mudar nada.
         */
        post: operations["publishEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/waitlist/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Total de inscrições na lista de espera
         * @description Só ADMIN.
         */
        get: operations["getWaitlistStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista os eventos que ainda vão começar
         * @description Só os publicados, do início mais próximo ao mais distante, paginados por cursor. A última página vem com nextPageToken null.
         */
        get: operations["listUpcomingEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{eventId}/registration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lê a própria inscrição no evento
         * @description Só a de quem chama: não há como ler a inscrição de outra pessoa. Sem inscrição, 404, exista o evento ou não.
         */
        get: operations["getMyRegistration"];
        /**
         * Inscreve quem chama no evento
         * @description Sem corpo. Idempotente pela chave evento + conta: repetir devolve a mesma inscrição, com a mesma data, por isso dispensa If-Match e Idempotency-Key (docs/adr/0016). Exige perfil completo e 18 anos.
         */
        put: operations["registerForEvent"];
        post?: never;
        /**
         * Cancela a própria inscrição no evento
         * @description Idempotente: sem inscrição, também responde 204. Só até o evento começar.
         */
        delete: operations["cancelMyRegistration"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{eventId}/rounds/{number}/pairing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lê o próprio par na rodada
         * @description O id da conta do par, ou null se quem chama ficou de fora nesta rodada. Sem lugar na rodada, 404, exista o evento ou a rodada ou não.
         */
        get: operations["getMyPairing"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lê um evento publicado ou cancelado
         * @description Sem capacidade, contagem nem inscritos. Um rascunho responde como um id que não existe.
         */
        get: operations["getEvent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Quem está logado
         * @description O front usa para saber se há sessão: 200 com o nome de exibição e se o perfil está completo, ou 401 sem sessão.
         */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/blocked-accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista quem o usuário bloqueou
         * @description Do bloqueio mais recente para o mais antigo, paginado por cursor. A última página vem com nextPageToken null.
         */
        get: operations["listBlockedAccounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lê o próprio perfil
         * @description Toda conta tem um perfil, vazio até a primeira edição. O ETag da resposta vai no If-Match da edição.
         */
        get: operations["getMyProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Edita o próprio perfil
         * @description Merge patch de um nível: campo ausente não muda, null apaga e valor troca. Nome, data de nascimento e região não podem ser apagados; a data de nascimento só pode ser informada uma vez e precisa ser de maior de idade. A edição é inteira ou nada.
         */
        patch: operations["editMyProfile"];
        trace?: never;
    };
    "/api/me/registrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista as próprias inscrições
         * @description Em eventos que ainda não acabaram, inclusive cancelados e em andamento, do início mais próximo ao mais distante, paginadas por cursor. A última página vem com nextPageToken null.
         */
        get: operations["listMyRegistrations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Denuncia outra conta
         * @description Cria a denúncia no estado OPEN, para a moderação. Denunciar não bloqueia: para isso, chame blockAccount. Cada conta pode fazer 10 denúncias por dia, repostas aos poucos.
         */
        post: operations["fileReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lê uma denúncia feita pelo usuário
         * @description Só quem denunciou a lê. A de outra pessoa responde como um id que não existe.
         */
        get: operations["getMyReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/waitlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Inscreve um e-mail na lista de espera
         * @description Pública. A resposta é a mesma para e-mail novo ou já inscrito, para não revelar quem está na lista. Limitada por IP (IPv6 por rede /64), com o estado compartilhado entre réplicas.
         */
        post: operations["joinWaitlist"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Encerra a sessão
         * @description Encerra a sessão web aqui, apagando-a do servidor, e devolve a URL de logout do Entra, para o front navegar até ela e sair também de lá. Exige o token CSRF no header X-XSRF-TOKEN. Sem sessão ativa a resposta é a mesma. A URL leva só client_id e post_logout_redirect_uri, nunca o ID token.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AdminEventResponse: {
            /**
             * Format: int32
             * @description Quantas pessoas podem se inscrever
             */
            capacity: number;
            /** @description Descrição curta, em parágrafos */
            description: string;
            /**
             * Format: date-time
             * @description Fim, em UTC; o evento já acabou neste instante
             */
            endsAt: string;
            /**
             * Format: uuid
             * @description Id do evento
             */
            id: string;
            /**
             * Format: int64
             * @description Quantas pessoas se inscreveram
             */
            registrationCount: number;
            /**
             * Format: date-time
             * @description Início, em UTC; o evento começou neste instante
             */
            startsAt: string;
            /**
             * @description Estado guardado: rascunho, publicado ou cancelado
             * @enum {string}
             */
            status: "DRAFT" | "PUBLISHED" | "CANCELLED";
            /** @description Título, em uma linha */
            title: string;
        };
        AdminRoundResponse: {
            /**
             * Format: uuid
             * @description Id do evento
             */
            eventId: string;
            /**
             * Format: int32
             * @description Número da rodada no evento
             */
            number: number;
            /**
             * Format: int32
             * @description Quantos pares se formaram
             */
            pairCount: number;
            /**
             * Format: int32
             * @description Quantas pessoas ficaram sem par nesta rodada
             */
            sittingOutCount: number;
            /**
             * Format: date-time
             * @description Quando a rodada começou, em UTC; não muda nas repetições do PUT
             */
            startedAt: string;
        };
        BlockedAccount: {
            /**
             * Format: uuid
             * @description Id da conta bloqueada
             */
            accountId: string;
            /**
             * Format: date-time
             * @description Quando o bloqueio foi feito
             */
            blockedAt: string;
        };
        BlockedAccountsResponse: {
            /** @description Bloqueios do mais recente para o mais antigo */
            items: components["schemas"]["BlockedAccount"][];
            /** @description Token da próxima página, ou null na última */
            nextPageToken: string | null;
        };
        CreateEventRequest: {
            /**
             * Format: int32
             * @description Quantas pessoas podem se inscrever
             */
            capacity: number;
            /** @description Descrição curta em parágrafos, sem caracteres invisíveis */
            description: string;
            /**
             * Format: date-time
             * @description Fim, ISO 8601 com fuso; depois do início e no máximo 12 horas após ele
             */
            endsAt: string;
            /**
             * Format: date-time
             * @description Início, ISO 8601 com fuso (Z ou -03:00); no futuro e até 365 dias à frente
             */
            startsAt: string;
            /** @description Título em uma linha, sem caracteres invisíveis; espaços nas pontas são removidos */
            title: string;
        };
        CurrentUserResponse: {
            /** @description Nome de exibição no Entra, ou null se o usuário não tiver nome */
            displayName: string | null;
            /** @description Se o perfil já tem o necessário para usar o Duora; se não, o front leva ao cadastro */
            profileComplete: boolean;
        };
        /** @description Só os campos a mudar. Campo ausente não muda; null apaga. */
        EditProfileRequest: {
            /** @description Apresentação curta, em parágrafos; vazio ou null apaga */
            bio?: string | null;
            /**
             * Format: date
             * @description Data de nascimento de maior de idade; informada uma vez, não muda nem é apagada
             */
            birthDate?: string | null;
            /** @description Nome que as outras pessoas veem, numa linha; não pode ser apagado */
            displayName?: string | null;
            /**
             * @description Estado, pelo código ISO 3166-2; não pode ser apagado
             * @enum {string|null}
             */
            region?: "BR-AC" | "BR-AL" | "BR-AP" | "BR-AM" | "BR-BA" | "BR-CE" | "BR-DF" | "BR-ES" | "BR-GO" | "BR-MA" | "BR-MT" | "BR-MS" | "BR-MG" | "BR-PA" | "BR-PB" | "BR-PR" | "BR-PE" | "BR-PI" | "BR-RJ" | "BR-RN" | "BR-RS" | "BR-RO" | "BR-RR" | "BR-SC" | "BR-SP" | "BR-SE" | "BR-TO" | null;
        };
        EventResponse: {
            /** @description Descrição curta, em parágrafos */
            description: string;
            /**
             * Format: date-time
             * @description Fim, em UTC; o evento já acabou neste instante
             */
            endsAt: string;
            /**
             * Format: uuid
             * @description Id do evento
             */
            id: string;
            /**
             * Format: date-time
             * @description Início, em UTC; o evento começou neste instante
             */
            startsAt: string;
            /**
             * @description Publicado ou cancelado; em andamento e encerrado se leem dos horários
             * @enum {string}
             */
            status: "PUBLISHED" | "CANCELLED";
            /** @description Título, em uma linha */
            title: string;
        };
        /** @description Um campo recusado e o motivo. Trate um code desconhecido como erro genérico do campo. */
        FieldError: {
            /**
             * @description REQUIRED: ausente, null, vazio ou apagado onde é obrigatório. TOO_SHORT e TOO_LONG: abaixo de minLength ou acima de maxLength. BELOW_MINIMUM e ABOVE_MAXIMUM: número ou instante fora da faixa (em birthDate, ABOVE_MAXIMUM é menor de idade e BELOW_MINIMUM idade implausível). INVALID_FORMAT: tipo ou formato errado. UNSUPPORTED_VALUE: fora da lista fechada. FORBIDDEN_CHARACTER: controle, invisível ou espaço especial. SELF_REFERENCE: a própria conta. UNKNOWN_FIELD: chave que o corpo não aceita. MALFORMED_BODY: o corpo não é um objeto JSON legível.
             * @enum {string}
             */
            code: "REQUIRED" | "TOO_SHORT" | "TOO_LONG" | "BELOW_MINIMUM" | "ABOVE_MAXIMUM" | "INVALID_FORMAT" | "UNSUPPORTED_VALUE" | "FORBIDDEN_CHARACTER" | "SELF_REFERENCE" | "UNKNOWN_FIELD" | "MALFORMED_BODY";
            /** @description Nome da propriedade no corpo JSON, como o cliente a enviou. Ausente quando o erro é do corpo inteiro (MALFORMED_BODY) ou numa chave desconhecida fora do formato de nome. */
            field?: string;
        };
        FileReportRequest: {
            /** @description Relato livre em parágrafos, sem caracteres invisíveis; obrigatório com o motivo OTHER. Vazio ou só com espaços conta como ausente. */
            description?: string | null;
            /**
             * @description Motivo, de uma lista fechada
             * @enum {string}
             */
            reason: "HARASSMENT" | "HATE_SPEECH" | "SEXUAL_CONTENT" | "VIOLENCE_OR_THREAT" | "SCAM_OR_SPAM" | "FAKE_PROFILE" | "SUSPECTED_MINOR" | "OTHER";
            /**
             * Format: uuid
             * @description Id da conta denunciada
             */
            reportedAccountId: string;
        };
        JoinWaitlistRequest: {
            /**
             * Format: email
             * @description Endereço de e-mail; espaços nas pontas são ignorados e a caixa é normalizada
             * @example ana@example.com
             */
            email: string;
        };
        LogoutResponse: {
            /**
             * Format: uri
             * @description URL de logout do Entra; o front navega até ela depois do 200
             */
            logoutUrl: string;
        };
        MyRegistrationResponse: {
            /**
             * Format: date-time
             * @description Fim do evento, em UTC
             */
            endsAt: string;
            /**
             * Format: uuid
             * @description Id do evento
             */
            eventId: string;
            /**
             * @description Estado do evento: um cancelado continua na lista, para a pessoa saber
             * @enum {string}
             */
            eventStatus: "PUBLISHED" | "CANCELLED";
            /**
             * Format: date-time
             * @description Quando a inscrição foi feita
             */
            registeredAt: string;
            /**
             * Format: date-time
             * @description Início do evento, em UTC
             */
            startsAt: string;
            /** @description Título do evento */
            title: string;
        };
        PageResponseEventResponse: {
            /** @description Itens da página, pelo início do evento */
            items: components["schemas"]["EventResponse"][];
            /** @description Token da próxima página, ou null na última */
            nextPageToken: string | null;
        };
        PageResponseMyRegistrationResponse: {
            /** @description Itens da página, pelo início do evento */
            items: components["schemas"]["MyRegistrationResponse"][];
            /** @description Token da próxima página, ou null na última */
            nextPageToken: string | null;
        };
        PairingResponse: {
            /**
             * Format: uuid
             * @description Id do evento
             */
            eventId: string;
            /**
             * Format: uuid
             * @description Id da conta do par nesta rodada, ou null se quem chama ficou de fora
             */
            partnerAccountId: string | null;
            /**
             * Format: int32
             * @description Número da rodada no evento
             */
            roundNumber: number;
        };
        /** @description Erro no formato RFC 9457. Sem stack trace, SQL nem nome de classe. */
        ProblemDetail: {
            detail?: string;
            /** Format: uri-reference */
            instance?: string;
            /** @description Correlation ID, o mesmo do header X-Request-Id; vem nos erros inesperados (500) */
            requestId?: string;
            /** Format: int32 */
            status: number;
            title: string;
            /** Format: uri-reference */
            type?: string;
        };
        ProfileResponse: {
            /** @description Apresentação, ou null */
            bio: string | null;
            /**
             * Format: date
             * @description Data de nascimento, ou null se ainda não informada
             */
            birthDate: string | null;
            /** @description Nome, data de nascimento de maior de idade e região preenchidos */
            complete: boolean;
            /** @description Nome de exibição, ou null se ainda não informado */
            displayName: string | null;
            /**
             * @description Estado, pelo código ISO 3166-2, ou null se ainda não informado
             * @enum {string|null}
             */
            region: "BR-AC" | "BR-AL" | "BR-AP" | "BR-AM" | "BR-BA" | "BR-CE" | "BR-DF" | "BR-ES" | "BR-GO" | "BR-MA" | "BR-MT" | "BR-MS" | "BR-MG" | "BR-PA" | "BR-PB" | "BR-PR" | "BR-PE" | "BR-PI" | "BR-RJ" | "BR-RN" | "BR-RS" | "BR-RO" | "BR-RR" | "BR-SC" | "BR-SP" | "BR-SE" | "BR-TO" | null;
        };
        RegistrationResponse: {
            /**
             * Format: uuid
             * @description Id do evento
             */
            eventId: string;
            /**
             * Format: date-time
             * @description Quando a inscrição foi feita; não muda nas repetições do PUT
             */
            registeredAt: string;
        };
        ReportResponse: {
            /**
             * Format: date-time
             * @description Quando a denúncia foi feita
             */
            createdAt: string;
            /** @description O relato, ou null se não houve */
            description: string | null;
            /**
             * Format: uuid
             * @description Id da denúncia
             */
            id: string;
            /** @enum {string} */
            reason: "HARASSMENT" | "HATE_SPEECH" | "SEXUAL_CONTENT" | "VIOLENCE_OR_THREAT" | "SCAM_OR_SPAM" | "FAKE_PROFILE" | "SUSPECTED_MINOR" | "OTHER";
            /**
             * Format: uuid
             * @description Id da conta denunciada
             */
            reportedAccountId: string;
            /**
             * @description Estado na moderação
             * @enum {string}
             */
            status: "OPEN";
        };
        /** @description Erro de validação do corpo no formato RFC 9457. Além do detail, em inglês e para pessoas, errors diz a máquinas qual campo falhou e por quê, sem repetir o valor. */
        ValidationProblemDetail: {
            detail?: string;
            /** @description Um item por campo recusado, ordenados por campo */
            errors?: components["schemas"]["FieldError"][];
            /** Format: uri-reference */
            instance?: string;
            /** @description Correlation ID, o mesmo do header X-Request-Id; vem nos erros inesperados (500) */
            requestId?: string;
            /** Format: int32 */
            status: number;
            title: string;
            /** Format: uri-reference */
            type?: string;
        };
        WaitlistStatsResponse: {
            /**
             * Format: int64
             * @description Inscrições na lista
             */
            total: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: {
        /** @description Correlation ID da requisição (trace id W3C); informe-o ao reportar um erro */
        RequestId: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    blockAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id da outra conta, como o app o recebe ao mostrar a pessoa */
                accountId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A conta está bloqueada */
            204: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bloqueio de si mesmo, ou id que não é UUID */
            400: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Sem credencial válida */
            401: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Sessão web sem o token CSRF no header X-XSRF-TOKEN */
            403: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Não há conta com esse id */
            404: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Erro inesperado */
            500: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    unblockAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id da outra conta, como o app o recebe ao mostrar a pessoa */
                accountId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A conta não está bloqueada por quem chama */
            204: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Id que não é UUID */
            400: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Sem credencial válida */
            401: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Sessão web sem o token CSRF no header X-XSRF-TOKEN */
            403: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Erro inesperado */
            500: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    createEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEventRequest"];
            };
        };
        responses: {
            /** @description O rascunho criado */
            201: {
                headers: {
                    /** @description Endereço do evento criado */
                    Location: string;
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEventResponse"];
                };
            };
            /** @description Campo ausente ou inválido (texto, horário sem fuso, início no passado ou além de um ano, duração acima de 12 horas, capacidade fora de 2 a 200), JSON malformado ou campo desconhecido */
            400: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblemDetail"];
                };
            };
            /** @description Sem credencial válida */
            401: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Sem o papel ADMIN */
            403: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Corpo em outro formato que não application/json */
            415: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Erro inesperado */
            500: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    getRound: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id do evento */
                eventId: string;
                /** @description Número da rodada no evento, a partir de 1 */
                number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A rodada */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminRoundResponse"];
                };
            };
            /** @description Id que não é UUID, ou número fora de 1 a 100 */
            400: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Sem credencial válida */
            401: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Sem o papel ADMIN */
            403: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description O evento não tem rodada com esse número */
            404: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Erro inesperado */
            500: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    startRound: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id do evento */
                eventId: string;
                /** @description Número da rodada no evento, a partir de 1 */
                number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A rodada que já existia */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminRoundResponse"];
                };
            };
            /** @description A rodada criada */
            201: {
                headers: {
                    /** @description Endereço da rodada */
                    Location: string;
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminRoundResponse"];
                };
            };
            /** @description Id que não é UUID, ou número fora de 1 a 100 */
            400: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Sem credencial válida */
            401: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Sem o papel ADMIN */
            403: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Não há evento com esse id */
            404: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description O evento não está em andamento (rascunho, cancelado, antes do início ou depois do fim), ou a rodada anterior ainda não começou */
            409: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Erro inesperado */
            500: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Outro pedido está iniciando a mesma rodada; nada foi gravado */
            503: {
                headers: {
                    /** @description Segundos até tentar de novo */
                    "Retry-After": number;
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    getAdminEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id do evento, como a criação o devolveu */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description O evento */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEventResponse"];
                };
            };
            /** @description Id que não é UUID */
            400: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Sem credencial válida */
            401: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Sem o papel ADMIN */
            403: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Não há evento com esse id */
            404: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Erro inesperado */
            500: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    cancelEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id do evento, como a criação o devolveu */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description O evento cancelado */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEventResponse"];
                };
            };
            /** @description Id que não é UUID */
            400: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Sem credencial válida */
            401: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Sem o papel ADMIN */
            403: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Não há evento com esse id */
            404: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description O evento já foi cancelado, já acabou ou mudou ao mesmo tempo por outra ação */
            409: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Erro inesperado */
            500: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    publishEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id do evento, como a criação o devolveu */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description O evento publicado */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEventResponse"];
                };
            };
            /** @description Id que não é UUID */
            400: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Sem credencial válida */
            401: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Sem o papel ADMIN */
            403: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Não há evento com esse id */
            404: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description O evento não é rascunho, já começou ou mudou ao mesmo tempo por outra ação */
            409: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Erro inesperado */
            500: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    getWaitlistStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaitlistStatsResponse"];
                };
            };
            /** @description Sem credencial válida */
            401: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Sem o papel ADMIN */
            403: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Erro inesperado */
            500: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    listUpcomingEvents: {
        parameters: {
            query?: {
                /** @description Quantos eventos no máximo nesta página */
                maxPageSize?: number;
                /** @description O nextPageToken da página anterior; ausente na primeira */
                pageToken?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Uma página dos eventos */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponseEventResponse"];
                };
            };
            /** @description maxPageSize fora de 1 a 50, ou pageToken que a API não gerou */
            400: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Sem credencial válida */
            401: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Erro inesperado */
            500: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    getMyRegistration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id do evento */
                eventId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A inscrição */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistrationResponse"];
                };
            };
            /** @description Id que não é UUID */
            400: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Sem credencial válida */
            401: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Quem chama não está inscrito nesse evento */
            404: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Erro inesperado */
            500: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    registerForEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id do evento */
                eventId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A inscrição que já existia */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistrationResponse"];
                };
            };
            /** @description A inscrição criada */
            201: {
                headers: {
                    /** @description Endereço da inscrição */
                    Location: string;
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistrationResponse"];
                };
            };
            /** @description Id que não é UUID */
            400: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Sem credencial válida */
            401: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Perfil incompleto ou menor de 18 anos, ou sessão web sem o token CSRF no header X-XSRF-TOKEN */
            403: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Evento inexistente ou rascunho */
            404: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Evento cancelado, já começado ou lotado */
            409: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Erro inesperado */
            500: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description O evento está ocupado com outras inscrições; nada foi gravado */
            503: {
                headers: {
                    /** @description Segundos até tentar de novo */
                    "Retry-After": number;
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    cancelMyRegistration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id do evento */
                eventId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Quem chama não está inscrito no evento */
            204: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Id que não é UUID */
            400: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Sem credencial válida */
            401: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Sessão web sem o token CSRF no header X-XSRF-TOKEN */
            403: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Evento inexistente ou rascunho */
            404: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description O evento já começou */
            409: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Erro inesperado */
            500: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    getMyPairing: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id do evento */
                eventId: string;
                /** @description Número da rodada no evento, a partir de 1 */
                number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description O lugar de quem chama na rodada */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairingResponse"];
                };
            };
            /** @description Id que não é UUID, ou número fora de 1 a 100 */
            400: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Sem credencial válida */
            401: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Quem chama não estava no sorteio dessa rodada */
            404: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Erro inesperado */
            500: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    getEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id do evento */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description O evento */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResponse"];
                };
            };
            /** @description Id que não é UUID */
            400: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Sem credencial válida */
            401: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Evento inexistente ou rascunho */
            404: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Erro inesperado */
            500: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserResponse"];
                };
            };
            /** @description Sem credencial válida */
            401: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Erro inesperado */
            500: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    listBlockedAccounts: {
        parameters: {
            query?: {
                /** @description Quantos bloqueios no máximo nesta página */
                maxPageSize?: number;
                /** @description O nextPageToken da página anterior; ausente na primeira */
                pageToken?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Uma página dos bloqueios */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlockedAccountsResponse"];
                };
            };
            /** @description maxPageSize fora de 1 a 100, ou pageToken que a API não gerou */
            400: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Sem credencial válida */
            401: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Erro inesperado */
            500: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    getMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description O perfil, com a versão no ETag */
            200: {
                headers: {
                    /** @description Versão do perfil, para mandar no If-Match da próxima edição */
                    ETag: string;
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            /** @description Sem credencial válida */
            401: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Erro inesperado */
            500: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    editMyProfile: {
        parameters: {
            query?: never;
            header: {
                /** @description O ETag da última leitura do perfil */
                "If-Match": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditProfileRequest"];
            };
        };
        responses: {
            /** @description O perfil editado, com a nova versão no ETag */
            200: {
                headers: {
                    /** @description Versão do perfil, para mandar no If-Match da próxima edição */
                    ETag: string;
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            /** @description Valor inválido, campo obrigatório apagado, JSON malformado ou campo desconhecido */
            400: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblemDetail"];
                };
            };
            /** @description Sem credencial válida */
            401: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Sessão web sem o token CSRF no header X-XSRF-TOKEN */
            403: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description A data de nascimento já foi informada e não muda */
            409: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description O If-Match não é o ETag atual: o perfil mudou desde a leitura, ou o valor não é um ETag */
            412: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Corpo em outro formato que não application/json */
            415: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Falta o If-Match */
            428: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Erro inesperado */
            500: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    listMyRegistrations: {
        parameters: {
            query?: {
                /** @description Quantas inscrições no máximo nesta página */
                maxPageSize?: number;
                /** @description O nextPageToken da página anterior; ausente na primeira */
                pageToken?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Uma página das inscrições */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponseMyRegistrationResponse"];
                };
            };
            /** @description maxPageSize fora de 1 a 50, ou pageToken que a API não gerou */
            400: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Sem credencial válida */
            401: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Erro inesperado */
            500: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    fileReport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FileReportRequest"];
            };
        };
        responses: {
            /** @description A denúncia criada */
            201: {
                headers: {
                    /** @description Endereço da denúncia criada */
                    Location: string;
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportResponse"];
                };
            };
            /** @description Denúncia de si mesmo, motivo OTHER sem descrição, descrição inválida, JSON malformado ou campo desconhecido */
            400: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblemDetail"];
                };
            };
            /** @description Sem credencial válida */
            401: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Sessão web sem o token CSRF no header X-XSRF-TOKEN */
            403: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Não há conta com o id denunciado */
            404: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Corpo em outro formato que não application/json */
            415: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Cota diária de denúncias desta conta esgotada */
            429: {
                headers: {
                    /** @description Segundos até a próxima denúncia ficar disponível */
                    "Retry-After": number;
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Erro inesperado */
            500: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Cota indisponível; a denúncia é recusada */
            503: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    getMyReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id da denúncia */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A denúncia */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportResponse"];
                };
            };
            /** @description Id que não é UUID */
            400: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Sem credencial válida */
            401: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Denúncia inexistente ou de outra pessoa */
            404: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Erro inesperado */
            500: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    joinWaitlist: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinWaitlistRequest"];
            };
        };
        responses: {
            /** @description Inscrição aceita, nova ou repetida */
            202: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description E-mail ausente ou inválido, JSON malformado ou campo desconhecido */
            400: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblemDetail"];
                };
            };
            /** @description Corpo em outro formato que não application/json */
            415: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Limite de inscrições deste cliente esgotado */
            429: {
                headers: {
                    /** @description Segundos até a próxima inscrição ser aceita */
                    "Retry-After": number;
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Erro inesperado */
            500: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Limite de inscrições indisponível; a inscrição é recusada */
            503: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessão encerrada; navegue até logoutUrl */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponse"];
                };
            };
            /** @description Sem o token CSRF no header X-XSRF-TOKEN; a sessão continua ativa */
            403: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Erro inesperado */
            500: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
}
