/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/accounts/{accountId}:block": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bloqueia outra conta
         * @description Idempotente: bloquear quem já está bloqueado também responde 204 e mantém a data do primeiro bloqueio. A resposta é a mesma se a outra pessoa tiver bloqueado você.
         */
        post: operations["blockAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{accountId}:unblock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Desfaz o próprio bloqueio de outra conta
         * @description Idempotente: sem bloqueio, ou com id que não é de conta, também responde 204. Um bloqueio que a outra pessoa fez continua valendo.
         */
        post: operations["unblockAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/waitlist/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Total de inscrições na lista de espera
         * @description Só ADMIN.
         */
        get: operations["getWaitlistStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Quem está logado
         * @description O front usa para saber se há sessão: 200 com o nome de exibição e se o perfil está completo, ou 401 sem sessão.
         */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/blocked-accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista quem o usuário bloqueou
         * @description Do bloqueio mais recente para o mais antigo, paginado por cursor. A última página vem com nextPageToken null.
         */
        get: operations["listBlockedAccounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lê o próprio perfil
         * @description Toda conta tem um perfil, vazio até a primeira edição. O ETag da resposta vai no If-Match da edição.
         */
        get: operations["getMyProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Edita o próprio perfil
         * @description Merge patch de um nível: campo ausente não muda, null apaga e valor troca. Nome, data de nascimento e região não podem ser apagados; a data de nascimento só pode ser informada uma vez e precisa ser de maior de idade. A edição é inteira ou nada.
         */
        patch: operations["editMyProfile"];
        trace?: never;
    };
    "/api/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Denuncia outra conta
         * @description Cria a denúncia no estado OPEN, para a moderação. Denunciar não bloqueia: para isso, chame blockAccount. Cada conta pode fazer 10 denúncias por dia, repostas aos poucos.
         */
        post: operations["fileReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lê uma denúncia feita pelo usuário
         * @description Só quem denunciou a lê. A de outra pessoa responde como um id que não existe.
         */
        get: operations["getMyReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/waitlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Inscreve um e-mail na lista de espera
         * @description Pública. A resposta é a mesma para e-mail novo ou já inscrito, para não revelar quem está na lista. Limitada por IP (IPv6 por rede /64), com o estado compartilhado entre réplicas.
         */
        post: operations["joinWaitlist"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BlockedAccount: {
            /**
             * Format: uuid
             * @description Id da conta bloqueada
             */
            accountId: string;
            /**
             * Format: date-time
             * @description Quando o bloqueio foi feito
             */
            blockedAt: string;
        };
        BlockedAccountsResponse: {
            /** @description Bloqueios do mais recente para o mais antigo */
            items: components["schemas"]["BlockedAccount"][];
            /** @description Token da próxima página, ou null na última */
            nextPageToken: string | null;
        };
        CurrentUserResponse: {
            /** @description Nome de exibição no Entra, ou null se o usuário não tiver nome */
            displayName: string | null;
            /** @description Se o perfil já tem o necessário para usar o Duora; se não, o front leva ao cadastro */
            profileComplete: boolean;
        };
        /** @description Só os campos a mudar. Campo ausente não muda; null apaga. */
        EditProfileRequest: {
            /** @description Apresentação curta, em parágrafos; vazio ou null apaga */
            bio?: string | null;
            /**
             * Format: date
             * @description Data de nascimento de maior de idade; informada uma vez, não muda nem é apagada
             */
            birthDate?: string | null;
            /** @description Nome que as outras pessoas veem, numa linha; não pode ser apagado */
            displayName?: string | null;
            /**
             * @description Estado, pelo código ISO 3166-2; não pode ser apagado
             * @enum {string|null}
             */
            region?: "BR-AC" | "BR-AL" | "BR-AP" | "BR-AM" | "BR-BA" | "BR-CE" | "BR-DF" | "BR-ES" | "BR-GO" | "BR-MA" | "BR-MT" | "BR-MS" | "BR-MG" | "BR-PA" | "BR-PB" | "BR-PR" | "BR-PE" | "BR-PI" | "BR-RJ" | "BR-RN" | "BR-RS" | "BR-RO" | "BR-RR" | "BR-SC" | "BR-SP" | "BR-SE" | "BR-TO" | null;
        };
        FileReportRequest: {
            /** @description Relato livre em parágrafos, sem caracteres invisíveis; obrigatório com o motivo OTHER. Vazio ou só com espaços conta como ausente. */
            description?: string | null;
            /**
             * @description Motivo, de uma lista fechada
             * @enum {string}
             */
            reason: "HARASSMENT" | "HATE_SPEECH" | "SEXUAL_CONTENT" | "VIOLENCE_OR_THREAT" | "SCAM_OR_SPAM" | "FAKE_PROFILE" | "SUSPECTED_MINOR" | "OTHER";
            /**
             * Format: uuid
             * @description Id da conta denunciada
             */
            reportedAccountId: string;
        };
        JoinWaitlistRequest: {
            /**
             * Format: email
             * @description Endereço de e-mail; espaços nas pontas são ignorados e a caixa é normalizada
             * @example ana@example.com
             */
            email: string;
        };
        /** @description Erro no formato RFC 9457. Sem stack trace, SQL nem nome de classe. */
        ProblemDetail: {
            detail?: string;
            /** Format: uri-reference */
            instance?: string;
            /** @description Correlation ID, o mesmo do header X-Request-Id; vem nos erros inesperados (500) */
            requestId?: string;
            /** Format: int32 */
            status: number;
            title: string;
            /** Format: uri-reference */
            type?: string;
        };
        ProfileResponse: {
            /** @description Apresentação, ou null */
            bio: string | null;
            /**
             * Format: date
             * @description Data de nascimento, ou null se ainda não informada
             */
            birthDate: string | null;
            /** @description Nome, data de nascimento de maior de idade e região preenchidos */
            complete: boolean;
            /** @description Nome de exibição, ou null se ainda não informado */
            displayName: string | null;
            /**
             * @description Estado, pelo código ISO 3166-2, ou null se ainda não informado
             * @enum {string|null}
             */
            region: "BR-AC" | "BR-AL" | "BR-AP" | "BR-AM" | "BR-BA" | "BR-CE" | "BR-DF" | "BR-ES" | "BR-GO" | "BR-MA" | "BR-MT" | "BR-MS" | "BR-MG" | "BR-PA" | "BR-PB" | "BR-PR" | "BR-PE" | "BR-PI" | "BR-RJ" | "BR-RN" | "BR-RS" | "BR-RO" | "BR-RR" | "BR-SC" | "BR-SP" | "BR-SE" | "BR-TO" | null;
        };
        ReportResponse: {
            /**
             * Format: date-time
             * @description Quando a denúncia foi feita
             */
            createdAt: string;
            /** @description O relato, ou null se não houve */
            description: string | null;
            /**
             * Format: uuid
             * @description Id da denúncia
             */
            id: string;
            /** @enum {string} */
            reason: "HARASSMENT" | "HATE_SPEECH" | "SEXUAL_CONTENT" | "VIOLENCE_OR_THREAT" | "SCAM_OR_SPAM" | "FAKE_PROFILE" | "SUSPECTED_MINOR" | "OTHER";
            /**
             * Format: uuid
             * @description Id da conta denunciada
             */
            reportedAccountId: string;
            /**
             * @description Estado na moderação
             * @enum {string}
             */
            status: "OPEN";
        };
        WaitlistStatsResponse: {
            /**
             * Format: int64
             * @description Inscrições na lista
             */
            total: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: {
        /** @description Correlation ID da requisição (trace id W3C); informe-o ao reportar um erro */
        RequestId: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    blockAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id da outra conta, como o app o recebe ao mostrar a pessoa */
                accountId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A conta está bloqueada */
            204: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bloqueio de si mesmo, ou id que não é UUID */
            400: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Sem credencial válida */
            401: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Sessão web sem o token CSRF no header X-XSRF-TOKEN */
            403: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Não há conta com esse id */
            404: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Erro inesperado */
            500: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    unblockAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id da outra conta, como o app o recebe ao mostrar a pessoa */
                accountId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A conta não está bloqueada por quem chama */
            204: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Id que não é UUID */
            400: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Sem credencial válida */
            401: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Sessão web sem o token CSRF no header X-XSRF-TOKEN */
            403: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Erro inesperado */
            500: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    getWaitlistStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaitlistStatsResponse"];
                };
            };
            /** @description Sem credencial válida */
            401: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Sem o papel ADMIN */
            403: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Erro inesperado */
            500: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserResponse"];
                };
            };
            /** @description Sem credencial válida */
            401: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Erro inesperado */
            500: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    listBlockedAccounts: {
        parameters: {
            query?: {
                /** @description Quantos bloqueios no máximo nesta página */
                maxPageSize?: number;
                /** @description O nextPageToken da página anterior; ausente na primeira */
                pageToken?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Uma página dos bloqueios */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlockedAccountsResponse"];
                };
            };
            /** @description maxPageSize fora de 1 a 100, ou pageToken que a API não gerou */
            400: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Sem credencial válida */
            401: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Erro inesperado */
            500: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    getMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description O perfil, com a versão no ETag */
            200: {
                headers: {
                    /** @description Versão do perfil, para mandar no If-Match da próxima edição */
                    ETag: string;
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            /** @description Sem credencial válida */
            401: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Erro inesperado */
            500: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    editMyProfile: {
        parameters: {
            query?: never;
            header: {
                /** @description O ETag da última leitura do perfil */
                "If-Match": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditProfileRequest"];
            };
        };
        responses: {
            /** @description O perfil editado, com a nova versão no ETag */
            200: {
                headers: {
                    /** @description Versão do perfil, para mandar no If-Match da próxima edição */
                    ETag: string;
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            /** @description Valor inválido, campo obrigatório apagado, JSON malformado ou campo desconhecido */
            400: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Sem credencial válida */
            401: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Sessão web sem o token CSRF no header X-XSRF-TOKEN */
            403: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description A data de nascimento já foi informada e não muda */
            409: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description O If-Match não é o ETag atual: o perfil mudou desde a leitura, ou o valor não é um ETag */
            412: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Corpo em outro formato que não application/json */
            415: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Falta o If-Match */
            428: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Erro inesperado */
            500: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    fileReport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FileReportRequest"];
            };
        };
        responses: {
            /** @description A denúncia criada */
            201: {
                headers: {
                    /** @description Endereço da denúncia criada */
                    Location: string;
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportResponse"];
                };
            };
            /** @description Denúncia de si mesmo, motivo OTHER sem descrição, descrição inválida, JSON malformado ou campo desconhecido */
            400: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Sem credencial válida */
            401: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Sessão web sem o token CSRF no header X-XSRF-TOKEN */
            403: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Não há conta com o id denunciado */
            404: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Corpo em outro formato que não application/json */
            415: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Cota diária de denúncias desta conta esgotada */
            429: {
                headers: {
                    /** @description Segundos até a próxima denúncia ficar disponível */
                    "Retry-After": number;
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Erro inesperado */
            500: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Cota indisponível; a denúncia é recusada */
            503: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    getMyReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id da denúncia */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A denúncia */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportResponse"];
                };
            };
            /** @description Id que não é UUID */
            400: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Sem credencial válida */
            401: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Denúncia inexistente ou de outra pessoa */
            404: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Erro inesperado */
            500: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    joinWaitlist: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinWaitlistRequest"];
            };
        };
        responses: {
            /** @description Inscrição aceita, nova ou repetida */
            202: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description E-mail ausente ou inválido, JSON malformado ou campo desconhecido */
            400: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Corpo em outro formato que não application/json */
            415: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Limite de inscrições deste cliente esgotado */
            429: {
                headers: {
                    /** @description Segundos até a próxima inscrição ser aceita */
                    "Retry-After": number;
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Erro inesperado */
            500: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Limite de inscrições indisponível; a inscrição é recusada */
            503: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
}
